/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ApplyRouteRouteImport } from './routes/apply/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as ApplyIndexRouteImport } from './routes/apply/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileAttendanceRouteImport } from './routes/profile/attendance'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities/$id'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as ApplyStatusRouteImport } from './routes/apply/status'
import { Route as AdminApplicationsRouteRouteImport } from './routes/admin/applications/route'
import { Route as OrgSlugIndexRouteImport } from './routes/org/$slug/index'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin/opportunities/index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as OrgSlugJoinRouteImport } from './routes/org/$slug/join'
import { Route as OrgSlugEventsRouteImport } from './routes/org/$slug/events'
import { Route as AdminOpportunitiesNewRouteImport } from './routes/admin/opportunities/new'
import { Route as OrgSlugSpaceIndexRouteImport } from './routes/org/$slug/space/index'
import { Route as OrgSlugAdminIndexRouteImport } from './routes/org/$slug/admin/index'
import { Route as OrgSlugSpaceBookingsRouteImport } from './routes/org/$slug/space/bookings'
import { Route as OrgSlugAdminSpaceRouteImport } from './routes/org/$slug/admin/space'
import { Route as OrgSlugAdminSetupRouteImport } from './routes/org/$slug/admin/setup'
import { Route as OrgSlugAdminSettingsRouteImport } from './routes/org/$slug/admin/settings'
import { Route as AdminOpportunitiesIdEditRouteImport } from './routes/admin/opportunities/$id/edit'
import { Route as OrgSlugAdminProgramsIndexRouteImport } from './routes/org/$slug/admin/programs/index'
import { Route as OrgSlugAdminMembersIndexRouteImport } from './routes/org/$slug/admin/members/index'
import { Route as OrgSlugAdminProgramsProgramIdRouteImport } from './routes/org/$slug/admin/programs/$programId'
import { Route as OrgSlugAdminMembersUserIdRouteImport } from './routes/org/$slug/admin/members/$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRouteRoute = ApplyRouteRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAttendanceRoute = ProfileAttendanceRouteImport.update({
  id: '/profile/attendance',
  path: '/profile/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyStatusRoute = ApplyStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const AdminApplicationsRouteRoute = AdminApplicationsRouteRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/org/$slug/',
  path: '/org/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminApplicationsRouteRoute,
} as any)
const OrgSlugJoinRoute = OrgSlugJoinRouteImport.update({
  id: '/org/$slug/join',
  path: '/org/$slug/join',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugEventsRoute = OrgSlugEventsRouteImport.update({
  id: '/org/$slug/events',
  path: '/org/$slug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesNewRoute = AdminOpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgSlugSpaceIndexRoute = OrgSlugSpaceIndexRouteImport.update({
  id: '/org/$slug/space/',
  path: '/org/$slug/space/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAdminIndexRoute = OrgSlugAdminIndexRouteImport.update({
  id: '/org/$slug/admin/',
  path: '/org/$slug/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugSpaceBookingsRoute = OrgSlugSpaceBookingsRouteImport.update({
  id: '/org/$slug/space/bookings',
  path: '/org/$slug/space/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAdminSpaceRoute = OrgSlugAdminSpaceRouteImport.update({
  id: '/org/$slug/admin/space',
  path: '/org/$slug/admin/space',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAdminSetupRoute = OrgSlugAdminSetupRouteImport.update({
  id: '/org/$slug/admin/setup',
  path: '/org/$slug/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAdminSettingsRoute = OrgSlugAdminSettingsRouteImport.update({
  id: '/org/$slug/admin/settings',
  path: '/org/$slug/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesIdEditRoute =
  AdminOpportunitiesIdEditRouteImport.update({
    id: '/opportunities/$id/edit',
    path: '/opportunities/$id/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const OrgSlugAdminProgramsIndexRoute =
  OrgSlugAdminProgramsIndexRouteImport.update({
    id: '/org/$slug/admin/programs/',
    path: '/org/$slug/admin/programs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugAdminMembersIndexRoute =
  OrgSlugAdminMembersIndexRouteImport.update({
    id: '/org/$slug/admin/members/',
    path: '/org/$slug/admin/members/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugAdminProgramsProgramIdRoute =
  OrgSlugAdminProgramsProgramIdRouteImport.update({
    id: '/org/$slug/admin/programs/$programId',
    path: '/org/$slug/admin/programs/$programId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugAdminMembersUserIdRoute =
  OrgSlugAdminMembersUserIdRouteImport.update({
    id: '/org/$slug/admin/members/$userId',
    path: '/org/$slug/admin/members/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/apply': typeof ApplyRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRouteRouteWithChildren
  '/apply/status': typeof ApplyStatusRoute
  '/matches/$id': typeof MatchesIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/attendance': typeof ProfileAttendanceRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/org/$slug/events': typeof OrgSlugEventsRoute
  '/org/$slug/join': typeof OrgSlugJoinRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
  '/org/$slug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/org/$slug/admin/setup': typeof OrgSlugAdminSetupRoute
  '/org/$slug/admin/space': typeof OrgSlugAdminSpaceRoute
  '/org/$slug/space/bookings': typeof OrgSlugSpaceBookingsRoute
  '/org/$slug/admin/': typeof OrgSlugAdminIndexRoute
  '/org/$slug/space/': typeof OrgSlugSpaceIndexRoute
  '/org/$slug/admin/members/$userId': typeof OrgSlugAdminMembersUserIdRoute
  '/org/$slug/admin/programs/$programId': typeof OrgSlugAdminProgramsProgramIdRoute
  '/org/$slug/admin/members/': typeof OrgSlugAdminMembersIndexRoute
  '/org/$slug/admin/programs/': typeof OrgSlugAdminProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apply/status': typeof ApplyStatusRoute
  '/matches/$id': typeof MatchesIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/attendance': typeof ProfileAttendanceRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin': typeof AdminIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/org/$slug/events': typeof OrgSlugEventsRoute
  '/org/$slug/join': typeof OrgSlugJoinRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
  '/org/$slug': typeof OrgSlugIndexRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
  '/org/$slug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/org/$slug/admin/setup': typeof OrgSlugAdminSetupRoute
  '/org/$slug/admin/space': typeof OrgSlugAdminSpaceRoute
  '/org/$slug/space/bookings': typeof OrgSlugSpaceBookingsRoute
  '/org/$slug/admin': typeof OrgSlugAdminIndexRoute
  '/org/$slug/space': typeof OrgSlugSpaceIndexRoute
  '/org/$slug/admin/members/$userId': typeof OrgSlugAdminMembersUserIdRoute
  '/org/$slug/admin/programs/$programId': typeof OrgSlugAdminProgramsProgramIdRoute
  '/org/$slug/admin/members': typeof OrgSlugAdminMembersIndexRoute
  '/org/$slug/admin/programs': typeof OrgSlugAdminProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/apply': typeof ApplyRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRouteRouteWithChildren
  '/apply/status': typeof ApplyStatusRoute
  '/matches/$id': typeof MatchesIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/attendance': typeof ProfileAttendanceRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/org/$slug/events': typeof OrgSlugEventsRoute
  '/org/$slug/join': typeof OrgSlugJoinRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
  '/org/$slug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/org/$slug/admin/setup': typeof OrgSlugAdminSetupRoute
  '/org/$slug/admin/space': typeof OrgSlugAdminSpaceRoute
  '/org/$slug/space/bookings': typeof OrgSlugSpaceBookingsRoute
  '/org/$slug/admin/': typeof OrgSlugAdminIndexRoute
  '/org/$slug/space/': typeof OrgSlugSpaceIndexRoute
  '/org/$slug/admin/members/$userId': typeof OrgSlugAdminMembersUserIdRoute
  '/org/$slug/admin/programs/$programId': typeof OrgSlugAdminProgramsProgramIdRoute
  '/org/$slug/admin/members/': typeof OrgSlugAdminMembersIndexRoute
  '/org/$slug/admin/programs/': typeof OrgSlugAdminProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/settings'
    | '/login'
    | '/admin/applications'
    | '/apply/status'
    | '/matches/$id'
    | '/opportunities/$id'
    | '/profile/attendance'
    | '/profile/edit'
    | '/admin/'
    | '/apply/'
    | '/matches/'
    | '/opportunities/'
    | '/orgs/'
    | '/profile/'
    | '/settings/'
    | '/admin/opportunities/new'
    | '/org/$slug/events'
    | '/org/$slug/join'
    | '/admin/applications/'
    | '/admin/opportunities/'
    | '/org/$slug/'
    | '/admin/opportunities/$id/edit'
    | '/org/$slug/admin/settings'
    | '/org/$slug/admin/setup'
    | '/org/$slug/admin/space'
    | '/org/$slug/space/bookings'
    | '/org/$slug/admin/'
    | '/org/$slug/space/'
    | '/org/$slug/admin/members/$userId'
    | '/org/$slug/admin/programs/$programId'
    | '/org/$slug/admin/members/'
    | '/org/$slug/admin/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/apply/status'
    | '/matches/$id'
    | '/opportunities/$id'
    | '/profile/attendance'
    | '/profile/edit'
    | '/admin'
    | '/apply'
    | '/matches'
    | '/opportunities'
    | '/orgs'
    | '/profile'
    | '/settings'
    | '/admin/opportunities/new'
    | '/org/$slug/events'
    | '/org/$slug/join'
    | '/admin/applications'
    | '/admin/opportunities'
    | '/org/$slug'
    | '/admin/opportunities/$id/edit'
    | '/org/$slug/admin/settings'
    | '/org/$slug/admin/setup'
    | '/org/$slug/admin/space'
    | '/org/$slug/space/bookings'
    | '/org/$slug/admin'
    | '/org/$slug/space'
    | '/org/$slug/admin/members/$userId'
    | '/org/$slug/admin/programs/$programId'
    | '/org/$slug/admin/members'
    | '/org/$slug/admin/programs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/settings'
    | '/login'
    | '/admin/applications'
    | '/apply/status'
    | '/matches/$id'
    | '/opportunities/$id'
    | '/profile/attendance'
    | '/profile/edit'
    | '/admin/'
    | '/apply/'
    | '/matches/'
    | '/opportunities/'
    | '/orgs/'
    | '/profile/'
    | '/settings/'
    | '/admin/opportunities/new'
    | '/org/$slug/events'
    | '/org/$slug/join'
    | '/admin/applications/'
    | '/admin/opportunities/'
    | '/org/$slug/'
    | '/admin/opportunities/$id/edit'
    | '/org/$slug/admin/settings'
    | '/org/$slug/admin/setup'
    | '/org/$slug/admin/space'
    | '/org/$slug/space/bookings'
    | '/org/$slug/admin/'
    | '/org/$slug/space/'
    | '/org/$slug/admin/members/$userId'
    | '/org/$slug/admin/programs/$programId'
    | '/org/$slug/admin/members/'
    | '/org/$slug/admin/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApplyRouteRoute: typeof ApplyRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  MatchesIdRoute: typeof MatchesIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  ProfileAttendanceRoute: typeof ProfileAttendanceRoute
  ProfileEditRoute: typeof ProfileEditRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  OrgSlugEventsRoute: typeof OrgSlugEventsRoute
  OrgSlugJoinRoute: typeof OrgSlugJoinRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugAdminSettingsRoute: typeof OrgSlugAdminSettingsRoute
  OrgSlugAdminSetupRoute: typeof OrgSlugAdminSetupRoute
  OrgSlugAdminSpaceRoute: typeof OrgSlugAdminSpaceRoute
  OrgSlugSpaceBookingsRoute: typeof OrgSlugSpaceBookingsRoute
  OrgSlugAdminIndexRoute: typeof OrgSlugAdminIndexRoute
  OrgSlugSpaceIndexRoute: typeof OrgSlugSpaceIndexRoute
  OrgSlugAdminMembersUserIdRoute: typeof OrgSlugAdminMembersUserIdRoute
  OrgSlugAdminProgramsProgramIdRoute: typeof OrgSlugAdminProgramsProgramIdRoute
  OrgSlugAdminMembersIndexRoute: typeof OrgSlugAdminMembersIndexRoute
  OrgSlugAdminProgramsIndexRoute: typeof OrgSlugAdminProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/attendance': {
      id: '/profile/attendance'
      path: '/profile/attendance'
      fullPath: '/profile/attendance'
      preLoaderRoute: typeof ProfileAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/status': {
      id: '/apply/status'
      path: '/status'
      fullPath: '/apply/status'
      preLoaderRoute: typeof ApplyStatusRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/org/$slug'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/opportunities'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminApplicationsRouteRoute
    }
    '/org/$slug/join': {
      id: '/org/$slug/join'
      path: '/org/$slug/join'
      fullPath: '/org/$slug/join'
      preLoaderRoute: typeof OrgSlugJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/events': {
      id: '/org/$slug/events'
      path: '/org/$slug/events'
      fullPath: '/org/$slug/events'
      preLoaderRoute: typeof OrgSlugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/new': {
      id: '/admin/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/admin/opportunities/new'
      preLoaderRoute: typeof AdminOpportunitiesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/org/$slug/space/': {
      id: '/org/$slug/space/'
      path: '/org/$slug/space'
      fullPath: '/org/$slug/space/'
      preLoaderRoute: typeof OrgSlugSpaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/': {
      id: '/org/$slug/admin/'
      path: '/org/$slug/admin'
      fullPath: '/org/$slug/admin/'
      preLoaderRoute: typeof OrgSlugAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/space/bookings': {
      id: '/org/$slug/space/bookings'
      path: '/org/$slug/space/bookings'
      fullPath: '/org/$slug/space/bookings'
      preLoaderRoute: typeof OrgSlugSpaceBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/space': {
      id: '/org/$slug/admin/space'
      path: '/org/$slug/admin/space'
      fullPath: '/org/$slug/admin/space'
      preLoaderRoute: typeof OrgSlugAdminSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/setup': {
      id: '/org/$slug/admin/setup'
      path: '/org/$slug/admin/setup'
      fullPath: '/org/$slug/admin/setup'
      preLoaderRoute: typeof OrgSlugAdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/settings': {
      id: '/org/$slug/admin/settings'
      path: '/org/$slug/admin/settings'
      fullPath: '/org/$slug/admin/settings'
      preLoaderRoute: typeof OrgSlugAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/$id/edit': {
      id: '/admin/opportunities/$id/edit'
      path: '/opportunities/$id/edit'
      fullPath: '/admin/opportunities/$id/edit'
      preLoaderRoute: typeof AdminOpportunitiesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/org/$slug/admin/programs/': {
      id: '/org/$slug/admin/programs/'
      path: '/org/$slug/admin/programs'
      fullPath: '/org/$slug/admin/programs/'
      preLoaderRoute: typeof OrgSlugAdminProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/members/': {
      id: '/org/$slug/admin/members/'
      path: '/org/$slug/admin/members'
      fullPath: '/org/$slug/admin/members/'
      preLoaderRoute: typeof OrgSlugAdminMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/programs/$programId': {
      id: '/org/$slug/admin/programs/$programId'
      path: '/org/$slug/admin/programs/$programId'
      fullPath: '/org/$slug/admin/programs/$programId'
      preLoaderRoute: typeof OrgSlugAdminProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/members/$userId': {
      id: '/org/$slug/admin/members/$userId'
      path: '/org/$slug/admin/members/$userId'
      fullPath: '/org/$slug/admin/members/$userId'
      preLoaderRoute: typeof OrgSlugAdminMembersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminApplicationsRouteRouteChildren {
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminApplicationsRouteRouteChildren: AdminApplicationsRouteRouteChildren =
  {
    AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  }

const AdminApplicationsRouteRouteWithChildren =
  AdminApplicationsRouteRoute._addFileChildren(
    AdminApplicationsRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminApplicationsRouteRoute: typeof AdminApplicationsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOpportunitiesNewRoute: typeof AdminOpportunitiesNewRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
  AdminOpportunitiesIdEditRoute: typeof AdminOpportunitiesIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApplicationsRouteRoute: AdminApplicationsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminOpportunitiesNewRoute: AdminOpportunitiesNewRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
  AdminOpportunitiesIdEditRoute: AdminOpportunitiesIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApplyRouteRouteChildren {
  ApplyStatusRoute: typeof ApplyStatusRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteRouteChildren: ApplyRouteRouteChildren = {
  ApplyStatusRoute: ApplyStatusRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteRouteWithChildren = ApplyRouteRoute._addFileChildren(
  ApplyRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApplyRouteRoute: ApplyRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  MatchesIdRoute: MatchesIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  ProfileAttendanceRoute: ProfileAttendanceRoute,
  ProfileEditRoute: ProfileEditRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  OrgSlugEventsRoute: OrgSlugEventsRoute,
  OrgSlugJoinRoute: OrgSlugJoinRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugAdminSettingsRoute: OrgSlugAdminSettingsRoute,
  OrgSlugAdminSetupRoute: OrgSlugAdminSetupRoute,
  OrgSlugAdminSpaceRoute: OrgSlugAdminSpaceRoute,
  OrgSlugSpaceBookingsRoute: OrgSlugSpaceBookingsRoute,
  OrgSlugAdminIndexRoute: OrgSlugAdminIndexRoute,
  OrgSlugSpaceIndexRoute: OrgSlugSpaceIndexRoute,
  OrgSlugAdminMembersUserIdRoute: OrgSlugAdminMembersUserIdRoute,
  OrgSlugAdminProgramsProgramIdRoute: OrgSlugAdminProgramsProgramIdRoute,
  OrgSlugAdminMembersIndexRoute: OrgSlugAdminMembersIndexRoute,
  OrgSlugAdminProgramsIndexRoute: OrgSlugAdminProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
